# Generated by Django 4.2.2 on 2023-06-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Negada', 'Negada'), ('Aprovada', 'Aprovada')], default='Negada', max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100)),
                ('valor_emprestimo', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
